resource "aws_db_subnet_group" "this" {
  name       = "${var.project}-db-subnet-group"
  subnet_ids = var.isolated_subnet_ids

  tags = {
    Name = "${var.project}-db-subnet-group"
  }
}

# Master password generated by Terraform, never hardcoded and never a
# variable default. Stored in Secrets Manager by the secrets module (which
# assembles the full DATABASE_URL from this value plus the instance's
# connection details) -- this module only holds it in state as the
# random_password resource.
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_db_instance" "this" {
  identifier     = "${var.project}-db"
  engine         = "postgres"
  engine_version = "16"

  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage
  storage_type      = "gp3"

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.rds_sg_id]

  multi_az                = false
  publicly_accessible     = false
  storage_encrypted       = true
  skip_final_snapshot     = true
  deletion_protection     = false
  apply_immediately       = true
  backup_retention_period = 0

  tags = {
    Name = "${var.project}-db"
  }
}
